### ISSUE TITLE
Not Usable

### ISSUE THREAD

**Issue by White-Devil-SD** [carbonid1/EmmetJSS#4]
Issue Type: <b>Bug</b>

I am unable to use emmet 

Extension version: 1.0.0
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by carbonid1** [comment]
Hey. What do you mean when say that you are unable to use emmet? Snippets are not showing in the VS Code when you type?

**Comment by White-Devil-SD** [comment]
M y   e m m e t   i s   i n s t a l l e d   a n d   e n a b l e d   b
u t   s t i l l   i t   d o e s   g e t   a c t i v a t e d


 S e n t   f r o m   M a i l   f o r   W i n d o w s   1 0

 F r o m :   A n d r i i   K o r i n
 S e n t :   S a t u r d a y ,   N o v e m b e r   1 6 ,   2 0 1 9   6
: 0 2   P M
 T o :   c a r b o n i d 1 / E m m e t J S S
 C c :   M o h a m m e d   D a n i s h ;   A u t h o r
 S u b j e c t :   R e :   [ c a r b o n i d 1 / E m m e t J S S ]   N
o t   U s a b l e   ( # 4 )

 H e y .   W h a t   d o   y o u   m e a n   w h e n   s a y   t h a t
  y o u   a r e   u n a b l e   t o   u s e   e m m e t ?   S n i p p
e t s   a r e   n o t   s h o w i n g   i n   t h e   V S   C o d e
w h e n   y o u   t y p e ?

 Y o u   a r e   r e c e i v i n g   t h i s   b e c a u s e   y o u
a u t h o r e d   t h e   t h r e a d .
 R e p l y   t o   t h i s   e m a i l   d i r e c t l y ,   v i e w
i t   o n   G i t H u b ,   o r   u n s u b s c r i b e .

**Comment by White-Devil-SD** [comment]
My emmet is installed and enabled but still it does get activated  Sent from Mail for Windows 10 From: Andrii KorinSent: Saturday, November 16, 2019 6:02 PMTo: carbonid1/EmmetJSSCc: Mohammed Danish; AuthorSubject: Re: [carbonid1/EmmetJSS] Not Usable (#4) Hey. What do you mean when say that you are unable to use emmet? Snippets are not showing in the VS Code when you type?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by carbonid1** [comment]
This extension is not for CSS but JSS  (CSS in JavaScript). Hence this issue is not related to the extension.

If you write your code in the .css file then you have some problems with your VS Code because Emmet for CSS is built in the IDE.
